<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nota [
    <!ELEMENT nota (para,de,titulo,contenido)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT contenido (#PCDATA)>
]>
<nota>
  <para>Pedro</para>
  <de>Laura</de>
  <titulo>Recordatorio</titulo>
  <contenido>A las 7:00h en la puerta del teatro</contenido>
</nota>