=== tasagaya/LND/xml/xsd/ej06/catalogolibros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.iesdomingoperezminik.es/1DAM/catalogo_libros"
	elementFormDefault="qualified"
	attributeFormDefault="qualified">
	<xs:element name="catalogo_libros">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="libro" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- Descripción del elemento libro -->
	<xs:element name="libro" type="tlibro"/>
	<!-- Definición del tipo tlibro -->
	<xs:complexType name="tlibro">
		<xs:sequence>
			<xs:element name="titulo" type="tnombre"/>
			<xs:element name="autor" type="tnombre" maxOccurs="unbounded"/>
			<xs:element name="fecha" type="tfecha"/>
			<xs:element name="isbn" type="tisbn"/>
			<xs:element name="editorial" type="tnombre"/>			
		</xs:sequence>
		<xs:attribute name="categoria">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="autobiografía"/>
					<xs:enumeration value="ficción"/>
					<xs:enumeration value="no ficción"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="stock" type="xs:string"/>
		<xs:attribute name="revisor" type="xs:string" default=""/>
	</xs:complexType>
	<!-- Definición del tipo fecha -->
	<xs:complexType name="tfecha">
		<xs:sequence>
			<xs:element name="mes" type="tmes" minOccurs="0"/>
			<xs:element name="anyo" type="tanyo"/>
		</xs:sequence>
	</xs:complexType>
	<!-- Definición del tipo tmes -->
	<xs:simpleType name="tmes">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="12"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definición del tipo tanyo -->
	<xs:simpleType name="tanyo">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1900"/>
			<xs:maxInclusive value="2011"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definición del tipo tnombre -->
	<xs:simpleType name="tnombre">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definición del tipo tisbn -->
	<xs:simpleType name="tisbn">
		<xs:restriction base="xs:string">
			<xs:minLength value="13"/>
			<xs:maxLength value="17"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== tasagaya/LND/xml/xsd/ej06/catalogo_libros.xml
<?xml version="1.0" encoding="utf-8"?>
<catalogo_libros xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
		xs:noNamespaceSchemaLocation="catalogolibros.xsd">
	<libro categoria="ficción" stock="Sí">
		<titulo>Los hombres que no amaban a las mujeres</titulo>
		<autor>Stieg Larsson</autor>
		<fecha>
			<anyo>2008</anyo>
		</fecha>
		<isbn>978-84-233-4044-6</isbn>
		<editorial>Destino</editorial>
	</libro>
	<libro categoria="No ficción" stock="No" revisor="Luís Rodrigo">
		<titulo>Java a través de ejemplos</titulo>
		<autor>Jesús Bobadilla</autor>
		<autor>Adela Sancho</autor>
		<fecha>
			<mes>Enero</mes>
			<anyo>2008</anyo>
		</fecha>
		<isbn>84-7897-549-7</isbn>
		<editorial>Ra-ma</editorial>
	</libro>
</catalogo_libros>
